# user-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: carldahlqvist/user-service:latest
          ports:
            - containerPort: 5002
          env:
            - name: MONGO_URI
              value: mongodb://mongo-service:27017/userdb
            - name: NODE_ENV
              value: k8s
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: jwt-secret
