# quiz-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
spec:
  type: ClusterIP
  selector:
    app: quiz-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001